server:
  port: 8081
# datasource
spring:
  application:
    name: eureka-provider
  datasource:
    url: jdbc:mysql://192.168.23.129:3306/TravalApp_JSP?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1123
    driver-class-name: com.mysql.cj.jdbc.Driver



# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.itheima.provider.domain
  # config-location:  # 指定mybatis的核心配置文件

eureka:
  instance:
    hostname: localhost # 主机名
    prefer-ip-address: true # 将当前实例的ip注册到eureka server 中。默认是false 注册主机名
    ip-address: 127.0.0.1 # 设置当前实例的ip
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port} # 设置web控制台显示的 实例id
    lease-renewal-interval-in-seconds: 5 # 每隔3 秒发一次心跳包
    lease-expiration-duration-in-seconds: 10 # 如果9秒没有发心跳包，服务器呀，你把我干掉吧~
  client:
    service-url:
      defaultZone: http://eureka-server1:8000/eureka,http://eureka-server2:9000/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信