server:
  port: 8082
eureka:
  instance:
    hostname: localhost # 主机名
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port} # 设置web控制台显示的 实例id
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://eureka-server1:8000/eureka,http://eureka-server2:9000/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信
spring:
 application:
  name: eureka-consumer # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径