# datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.23.129:3306/db5?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1123
    driver-class-name: com.mysql.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.itheima.springboot_mybatis.domain

  # config-location:  # 指定mybatis的核心配置文件