server:
  port: 8000
eureka:
  instance:
    hostname: eureka-server1
  client:
    service-url:
     defaultZone: http://eureka-server2:9000/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #剔除服务间隔（毫秒）
spring:
  application:
    name: eureka-server-ha