spring:
  application.name: hystrix-monitor
server:
  port: 8888
turbine:
  combine-host-port: true
  # 配置需要监控的服务名称列表
  app-config: eureka-provider,eureka-consumer
  cluster-name-expression: "'default'"
  aggregator:
    cluster-config: default
  #instanceUrlSuffix: /actuator/hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:8000/eureka,http://eureka-server2:9000/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信