new Vue({
    el:"#app",
    data:{
        //user类
        user:{},
        //userList数组
        userList:[],
        ids:[]
    },
    methods:{
        findById(id){
            //根据id查询
            axios.get("/vueDemo/user/findById?id="+id).then(rep=>{
                //获取响应对象
                this.user=rep.data;
            });
            //打开末代窗口
            $("#myModal").modal("show");
            },
        //查询所有页面加载时查询所有用户信息并显示在页面上
        findAll(){
            //异步请求
            axios.get("/vueDemo/user/findAll").then(rep=>{//箭头函数
                //获取响应数据
                this.userList=rep.data;
            }).catch((error)=>{
                alert("fail"+error);
            });
        },
        //根据id删除
        deleteByIds(){
            alert(this.ids);
            axios.get("/vueDemo/user/deleteByIds?ids="+this.ids).then(rep=>{
                this.ids=[];
                this.findAll();
            })
        },
        //新增功能
        save(){
            //发送请求
            axios.post("/vueDemo/user/save","userStr="+JSON.stringify(this.user)).then(rep=>{
                this.findAll();
            });
        },
        //更新
        update(){
            //发送请求
            let _this=this;
            axios.post("/vueDemo/user/update","u="+JSON.stringify(_this.user)).then(rep=>{
                this.findAll();
            });
        },
        //打开新增页面
        openSave(){
            this.user={};
            $("#myModal1").modal("show");
        },
    },
    //钩子函数
    created(){
        this.findAll();
    }
});